/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guidonrac;

import daodonrac.DuongDi;
import daodonrac.DAO_DonRac;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Hau Depp Troaiiii ^^
 */
public class GuiDonRac extends javax.swing.JFrame {

    /**
     * Creates new form MapDoRac
     */
    DuongDi mtTP[][] = new DuongDi[20][20]; // chua cost duong di
    Random generator = new Random();
    int mtKe[][] = new int[20][20]; //
    int luuDuongTam[] = new int[20];//luu chu trình hiện tại. ktra xem phải hamilton hay k 
    int Heuristic[] = new int[20];
    ;// tung` di qua r
    int quan = 19;
    ArrayList<ArrayList> luuDuongDi = new ArrayList<>();//luu chu trinh hamilton trong đường đi tạm
    int d = 0;//so duong di(chu trinh)
    int index = 0;//chu trinh tai luuduongdi[index] ngan nhat
    int min = 0;//cost thap nhat de di
    ArrayList<Integer> ketQua = new ArrayList<>();//
    int quanBatDau = 1;
    int indexdi = 0; //bntNext

    public GuiDonRac() {
        initComponents();
        this.setSize(1400, 700);
        this.setTitle("Thu Gom Rác Trong TP.HCM");
        initCost(); // ramdom cost
        initMatran();//tạo ma trận để chưa data thêm mtTP vs mtKe
        luuDuongTam[0] = 1;
        int i = 1;
        d = 0;
        Hamilton(luuDuongTam, Heuristic, i);//i chay từ 1 đến 19
//        inmanhinhchutrinh();
//        inmanhinhmtKe();
        timIndexNganNhat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        q8 = new javax.swing.JButton();
        qBinhTan = new javax.swing.JButton();
        q12 = new javax.swing.JButton();
        q5 = new javax.swing.JButton();
        qGoVap = new javax.swing.JButton();
        qTanBinh = new javax.swing.JButton();
        q11 = new javax.swing.JButton();
        q6 = new javax.swing.JButton();
        qTanPhu = new javax.swing.JButton();
        q10 = new javax.swing.JButton();
        qPhuNhuan = new javax.swing.JButton();
        q3 = new javax.swing.JButton();
        q1 = new javax.swing.JButton();
        qBinhThanh = new javax.swing.JButton();
        q2 = new javax.swing.JButton();
        q4 = new javax.swing.JButton();
        qThuDuc = new javax.swing.JButton();
        q9 = new javax.swing.JButton();
        q7 = new javax.swing.JButton();
        d6_8 = new javax.swing.JSeparator();
        d17_19 = new javax.swing.JSeparator();
        d12_17 = new javax.swing.JSeparator();
        d3_5 = new javax.swing.JSeparator();
        d11_18 = new javax.swing.JSeparator();
        d6_11 = new javax.swing.JSeparator();
        d17_18 = new javax.swing.JSeparator();
        d8_19 = new javax.swing.JSeparator();
        d4_8 = new javax.swing.JSeparator();
        d1_5 = new javax.swing.JSeparator();
        d6_19 = new javax.swing.JSeparator();
        d11_17 = new javax.swing.JSeparator();
        d3_10 = new javax.swing.JSeparator();
        d10_18 = new javax.swing.JSeparator();
        d4_5 = new javax.swing.JSeparator();
        d5_10 = new javax.swing.JSeparator();
        d15_18 = new javax.swing.JSeparator();
        d10_11 = new javax.swing.JSeparator();
        d3_18 = new javax.swing.JSeparator();
        d5_11 = new javax.swing.JSeparator();
        d5_6 = new javax.swing.JSeparator();
        d9_13 = new javax.swing.JSeparator();
        d12_16 = new javax.swing.JSeparator();
        d1_4 = new javax.swing.JSeparator();
        d1_3 = new javax.swing.JSeparator();
        d1_15 = new javax.swing.JSeparator();
        d7_8 = new javax.swing.JSeparator();
        d15_16 = new javax.swing.JSeparator();
        d4_7 = new javax.swing.JSeparator();
        d3_15 = new javax.swing.JSeparator();
        d1_2 = new javax.swing.JSeparator();
        d1_14 = new javax.swing.JSeparator();
        d14_16 = new javax.swing.JSeparator();
        d13_16 = new javax.swing.JSeparator();
        d13_14 = new javax.swing.JSeparator();
        d16_18 = new javax.swing.JSeparator();
        d2_14 = new javax.swing.JSeparator();
        d2_9 = new javax.swing.JSeparator();
        d2_7 = new javax.swing.JSeparator();
        d12_13 = new javax.swing.JSeparator();
        d14_15 = new javax.swing.JSeparator();
        d5_8 = new javax.swing.JSeparator();
        c1_2 = new javax.swing.JLabel();
        c2_9 = new javax.swing.JLabel();
        c13_14 = new javax.swing.JLabel();
        c1_14 = new javax.swing.JLabel();
        c14_15 = new javax.swing.JLabel();
        c14_16 = new javax.swing.JLabel();
        c13_16 = new javax.swing.JLabel();
        c2_7 = new javax.swing.JLabel();
        c1_5 = new javax.swing.JLabel();
        c1_3 = new javax.swing.JLabel();
        c15_18 = new javax.swing.JLabel();
        c3_18 = new javax.swing.JLabel();
        c3_10 = new javax.swing.JLabel();
        c10_18 = new javax.swing.JLabel();
        c12_16 = new javax.swing.JLabel();
        c17_18 = new javax.swing.JLabel();
        c11_17 = new javax.swing.JLabel();
        c1_4 = new javax.swing.JLabel();
        c4_7 = new javax.swing.JLabel();
        c4_5 = new javax.swing.JLabel();
        c5_8 = new javax.swing.JLabel();
        c5_11 = new javax.swing.JLabel();
        c10_11 = new javax.swing.JLabel();
        c5_10 = new javax.swing.JLabel();
        c6_19 = new javax.swing.JLabel();
        c8_19 = new javax.swing.JLabel();
        c4_8 = new javax.swing.JLabel();
        c7_8 = new javax.swing.JLabel();
        c12_17 = new javax.swing.JLabel();
        c17_19 = new javax.swing.JLabel();
        c9_13 = new javax.swing.JLabel();
        c2_14 = new javax.swing.JLabel();
        c3_5 = new javax.swing.JLabel();
        c5_6 = new javax.swing.JLabel();
        c6_11 = new javax.swing.JLabel();
        c1_15 = new javax.swing.JLabel();
        c15_16 = new javax.swing.JLabel();
        c16_18 = new javax.swing.JLabel();
        c6_8 = new javax.swing.JLabel();
        c11_18 = new javax.swing.JLabel();
        c3_15 = new javax.swing.JLabel();
        c12_13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbDuongDi = new javax.swing.JLabel();
        lbChiPhi = new javax.swing.JLabel();
        btnTinhToan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDuongDi = new javax.swing.JTextArea();
        btnChay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtQuanXuatPhat = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        btnChonLai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ThuDuc = new javax.swing.JButton();
        BinhThanh = new javax.swing.JButton();
        PhuNhuan = new javax.swing.JButton();
        GoVap = new javax.swing.JButton();
        TanPhu = new javax.swing.JButton();
        TanBinh = new javax.swing.JButton();
        BinhTan = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        q8.setText("8");
        jPanel1.add(q8);
        q8.setBounds(150, 430, 70, 120);

        qBinhTan.setText("Bình Tân");
        jPanel1.add(qBinhTan);
        qBinhTan.setBounds(20, 360, 80, 110);

        q12.setText("12");
        jPanel1.add(q12);
        q12.setBounds(20, 0, 70, 70);

        q5.setText("5");
        jPanel1.add(q5);
        q5.setBounds(360, 260, 90, 190);

        qGoVap.setText("Gò Vấp");
        jPanel1.add(qGoVap);
        qGoVap.setBounds(150, 20, 70, 60);

        qTanBinh.setText("Tân Bình");
        qTanBinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qTanBinhActionPerformed(evt);
            }
        });
        jPanel1.add(qTanBinh);
        qTanBinh.setBounds(140, 110, 80, 100);

        q11.setText("11");
        jPanel1.add(q11);
        q11.setBounds(150, 250, 70, 60);

        q6.setText("6");
        jPanel1.add(q6);
        q6.setBounds(150, 330, 70, 60);

        qTanPhu.setText("Tân Phú");
        jPanel1.add(qTanPhu);
        qTanPhu.setBounds(20, 160, 80, 110);

        q10.setText("10");
        jPanel1.add(q10);
        q10.setBounds(260, 180, 70, 100);

        qPhuNhuan.setText("Phú Nhuận");
        jPanel1.add(qPhuNhuan);
        qPhuNhuan.setBounds(360, 60, 90, 70);

        q3.setText("3");
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });
        jPanel1.add(q3);
        q3.setBounds(360, 150, 90, 70);

        q1.setText("1");
        jPanel1.add(q1);
        q1.setBounds(500, 103, 80, 290);

        qBinhThanh.setText("Bình Thạnh");
        jPanel1.add(qBinhThanh);
        qBinhThanh.setBounds(620, 40, 100, 90);

        q2.setText("2");
        jPanel1.add(q2);
        q2.setBounds(630, 220, 80, 110);

        q4.setText("4");
        q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4ActionPerformed(evt);
            }
        });
        jPanel1.add(q4);
        q4.setBounds(640, 370, 70, 140);

        qThuDuc.setText("Thủ Đức");
        qThuDuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qThuDucActionPerformed(evt);
            }
        });
        jPanel1.add(qThuDuc);
        qThuDuc.setBounds(770, 0, 90, 90);

        q9.setText("9");
        jPanel1.add(q9);
        q9.setBounds(770, 213, 70, 70);

        q7.setText("7");
        q7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7ActionPerformed(evt);
            }
        });
        jPanel1.add(q7);
        q7.setBounds(770, 303, 70, 250);

        d6_8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(d6_8);
        d6_8.setBounds(180, 390, 10, 40);

        d17_19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(d17_19);
        d17_19.setBounds(60, 270, 10, 90);

        d12_17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(d12_17);
        d12_17.setBounds(60, 70, 10, 90);

        d3_5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(d3_5);
        d3_5.setBounds(410, 220, 10, 40);

        d11_18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(d11_18);
        d11_18.setBounds(180, 210, 10, 40);

        d6_11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(d6_11);
        d6_11.setBounds(180, 310, 10, 20);
        jPanel1.add(d17_18);
        d17_18.setBounds(100, 180, 40, 20);
        jPanel1.add(d8_19);
        d8_19.setBounds(100, 450, 50, 20);
        jPanel1.add(d4_8);
        d4_8.setBounds(220, 490, 420, 10);
        jPanel1.add(d1_5);
        d1_5.setBounds(450, 320, 50, 20);
        jPanel1.add(d6_19);
        d6_19.setBounds(100, 370, 50, 20);
        jPanel1.add(d11_17);
        d11_17.setBounds(100, 260, 50, 10);
        jPanel1.add(d3_10);
        d3_10.setBounds(330, 200, 30, 10);
        jPanel1.add(d10_18);
        d10_18.setBounds(220, 200, 40, 10);
        jPanel1.add(d4_5);
        d4_5.setBounds(450, 430, 190, 10);
        jPanel1.add(d5_10);
        d5_10.setBounds(330, 270, 30, 10);
        jPanel1.add(d15_18);
        d15_18.setBounds(220, 120, 140, 10);
        jPanel1.add(d10_11);
        d10_11.setBounds(220, 260, 40, 10);
        jPanel1.add(d3_18);
        d3_18.setBounds(220, 160, 140, 10);
        jPanel1.add(d5_11);
        d5_11.setBounds(220, 300, 140, 10);
        jPanel1.add(d5_6);
        d5_6.setBounds(220, 360, 140, 10);

        d9_13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(d9_13);
        d9_13.setBounds(810, 90, 10, 130);
        jPanel1.add(d12_16);
        d12_16.setBounds(90, 60, 60, 20);
        jPanel1.add(d1_4);
        d1_4.setBounds(580, 380, 60, 20);
        jPanel1.add(d1_3);
        d1_3.setBounds(450, 180, 50, 20);
        jPanel1.add(d1_15);
        d1_15.setBounds(450, 110, 50, 20);
        jPanel1.add(d7_8);
        d7_8.setBounds(220, 530, 550, 10);
        jPanel1.add(d15_16);
        d15_16.setBounds(220, 70, 140, 10);
        jPanel1.add(d4_7);
        d4_7.setBounds(710, 390, 60, 20);

        d3_15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(d3_15);
        d3_15.setBounds(410, 130, 10, 20);
        jPanel1.add(d1_2);
        d1_2.setBounds(580, 250, 50, 20);
        jPanel1.add(d1_14);
        d1_14.setBounds(580, 120, 40, 20);
        jPanel1.add(d14_16);
        d14_16.setBounds(220, 50, 400, 10);
        jPanel1.add(d13_16);
        d13_16.setBounds(220, 30, 550, 10);
        jPanel1.add(d13_14);
        d13_14.setBounds(710, 80, 60, 20);

        d16_18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(d16_18);
        d16_18.setBounds(180, 80, 10, 30);

        d2_14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(d2_14);
        d2_14.setBounds(660, 130, 10, 90);
        jPanel1.add(d2_9);
        d2_9.setBounds(710, 250, 60, 20);
        jPanel1.add(d2_7);
        d2_7.setBounds(710, 320, 60, 20);
        jPanel1.add(d12_13);
        d12_13.setBounds(90, 10, 680, 10);
        jPanel1.add(d14_15);
        d14_15.setBounds(450, 80, 170, 10);
        jPanel1.add(d5_8);
        d5_8.setBounds(220, 440, 140, 10);

        c1_2.setText("jLabel1");
        jPanel1.add(c1_2);
        c1_2.setBounds(590, 230, 34, 14);

        c2_9.setText("jLabel2");
        jPanel1.add(c2_9);
        c2_9.setBounds(720, 230, 34, 14);

        c13_14.setText("jLabel3");
        jPanel1.add(c13_14);
        c13_14.setBounds(730, 60, 34, 14);

        c1_14.setText("jLabel4");
        jPanel1.add(c1_14);
        c1_14.setBounds(580, 100, 34, 14);

        c14_15.setText("jLabel5");
        jPanel1.add(c14_15);
        c14_15.setBounds(520, 60, 34, 14);

        c14_16.setText("jLabel6");
        jPanel1.add(c14_16);
        c14_16.setBounds(450, 34, 34, 20);

        c13_16.setText("jLabel7");
        jPanel1.add(c13_16);
        c13_16.setBounds(310, 10, 34, 14);

        c2_7.setText("jLabel9");
        jPanel1.add(c2_7);
        c2_7.setBounds(720, 300, 34, 14);

        c1_5.setText("jLabel10");
        jPanel1.add(c1_5);
        c1_5.setBounds(460, 300, 40, 14);

        c1_3.setText("jLabel11");
        jPanel1.add(c1_3);
        c1_3.setBounds(450, 160, 40, 14);

        c15_18.setText("jLabel12");
        jPanel1.add(c15_18);
        c15_18.setBounds(270, 100, 40, 14);

        c3_18.setText("jLabel13");
        jPanel1.add(c3_18);
        c3_18.setBounds(270, 140, 40, 14);

        c3_10.setText("jLabel14");
        jPanel1.add(c3_10);
        c3_10.setBounds(320, 180, 40, 14);

        c10_18.setText("jLabel15");
        jPanel1.add(c10_18);
        c10_18.setBounds(220, 180, 40, 14);

        c12_16.setText("jLabel16");
        jPanel1.add(c12_16);
        c12_16.setBounds(100, 40, 40, 14);

        c17_18.setText("jLabel17");
        jPanel1.add(c17_18);
        c17_18.setBounds(100, 160, 40, 14);

        c11_17.setText("jLabel18");
        jPanel1.add(c11_17);
        c11_17.setBounds(100, 240, 40, 14);

        c1_4.setText("jLabel19");
        jPanel1.add(c1_4);
        c1_4.setBounds(590, 360, 40, 14);

        c4_7.setText("jLabel20");
        jPanel1.add(c4_7);
        c4_7.setBounds(720, 370, 40, 14);

        c4_5.setText("jLabel21");
        jPanel1.add(c4_5);
        c4_5.setBounds(520, 410, 40, 14);

        c5_8.setText("jLabel22");
        jPanel1.add(c5_8);
        c5_8.setBounds(270, 420, 40, 14);

        c5_11.setText("jLabel23");
        jPanel1.add(c5_11);
        c5_11.setBounds(270, 280, 40, 14);

        c10_11.setText("jLabel24");
        jPanel1.add(c10_11);
        c10_11.setBounds(220, 240, 40, 14);

        c5_10.setText("jLabel25");
        jPanel1.add(c5_10);
        c5_10.setBounds(330, 250, 40, 14);

        c6_19.setText("jLabel26");
        jPanel1.add(c6_19);
        c6_19.setBounds(100, 350, 40, 14);

        c8_19.setText("jLabel27");
        jPanel1.add(c8_19);
        c8_19.setBounds(100, 430, 40, 14);

        c4_8.setText("jLabel28");
        jPanel1.add(c4_8);
        c4_8.setBounds(390, 470, 40, 14);

        c7_8.setText("jLabel29");
        jPanel1.add(c7_8);
        c7_8.setBounds(440, 510, 40, 14);

        c12_17.setText("jLabel30");
        jPanel1.add(c12_17);
        c12_17.setBounds(20, 120, 40, 14);

        c17_19.setText("jLabel31");
        jPanel1.add(c17_19);
        c17_19.setBounds(20, 320, 40, 14);

        c9_13.setText("jLabel32");
        jPanel1.add(c9_13);
        c9_13.setBounds(770, 150, 40, 14);

        c2_14.setText("c2_14");
        jPanel1.add(c2_14);
        c2_14.setBounds(620, 170, 29, 14);

        c3_5.setText("jLabel34");
        jPanel1.add(c3_5);
        c3_5.setBounds(370, 230, 40, 20);

        c5_6.setText("jLabel35");
        jPanel1.add(c5_6);
        c5_6.setBounds(270, 340, 40, 14);

        c6_11.setText("jLabel36");
        jPanel1.add(c6_11);
        c6_11.setBounds(140, 310, 40, 14);

        c1_15.setText("jLabel37");
        jPanel1.add(c1_15);
        c1_15.setBounds(460, 90, 40, 14);

        c15_16.setText("jLabel38");
        jPanel1.add(c15_16);
        c15_16.setBounds(270, 50, 40, 20);

        c16_18.setText("jLabel39");
        jPanel1.add(c16_18);
        c16_18.setBounds(140, 90, 40, 14);

        c6_8.setText("jLabel40");
        jPanel1.add(c6_8);
        c6_8.setBounds(140, 400, 40, 14);

        c11_18.setText("jLabel41");
        jPanel1.add(c11_18);
        c11_18.setBounds(140, 220, 40, 14);

        c3_15.setText("jLabel42");
        jPanel1.add(c3_15);
        c3_15.setBounds(370, 130, 40, 14);

        c12_13.setText("jLabel8");
        jPanel1.add(c12_13);
        c12_13.setBounds(520, -6, 34, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 590);

        lbDuongDi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbDuongDi.setText("Đường Đi:");

        lbChiPhi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbChiPhi.setText("Chi Phí:");

        btnTinhToan.setText("Tính Toán");
        btnTinhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhToanActionPerformed(evt);
            }
        });

        txtDuongDi.setColumns(20);
        txtDuongDi.setRows(5);
        txtDuongDi.setEnabled(false);
        jScrollPane1.setViewportView(txtDuongDi);

        btnChay.setText("Chạy");
        btnChay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Quận xuất phát:");

        txtQuanXuatPhat.setText("1");
        txtQuanXuatPhat.setEnabled(false);

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setEnabled(false);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnChonLai.setText("Chọn lại");
        btnChonLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonLaiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Chú thích");

        jLabel4.setText("13");

        jLabel5.setText("14");

        jLabel6.setText("15");

        jLabel7.setText("16");

        jLabel8.setText("17");

        jLabel9.setText("18");

        jLabel10.setText("19");

        ThuDuc.setText("Thủ Đức");
        ThuDuc.setEnabled(false);
        ThuDuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThuDucActionPerformed(evt);
            }
        });

        BinhThanh.setText("Bình Thạnh");
        BinhThanh.setEnabled(false);
        BinhThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinhThanhActionPerformed(evt);
            }
        });

        PhuNhuan.setText("Phú Nhuận");
        PhuNhuan.setEnabled(false);
        PhuNhuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhuNhuanActionPerformed(evt);
            }
        });

        GoVap.setText("Gò Vấp");
        GoVap.setEnabled(false);
        GoVap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoVapActionPerformed(evt);
            }
        });

        TanPhu.setText("Tân Phú");
        TanPhu.setEnabled(false);
        TanPhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanPhuActionPerformed(evt);
            }
        });

        TanBinh.setText("Tân Bình");
        TanBinh.setEnabled(false);
        TanBinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanBinhActionPerformed(evt);
            }
        });

        BinhTan.setText("Bình Tân");
        BinhTan.setEnabled(false);
        BinhTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinhTanActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnXacNhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChonLai)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ThuDuc)
                                            .addComponent(BinhThanh)
                                            .addComponent(PhuNhuan)
                                            .addComponent(GoVap)
                                            .addComponent(TanPhu)
                                            .addComponent(BinhTan)
                                            .addComponent(TanBinh))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lbChiPhi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbDuongDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(btnTinhToan))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuanXuatPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnChay, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuanXuatPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan)
                    .addComponent(btnChonLai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ThuDuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BinhThanh)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhuNhuan)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GoVap)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TanPhu)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TanBinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BinhTan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDuongDi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTinhToan)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChay)
                    .addComponent(btnNext))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(860, 0, 320, 620);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem3.setText("Giáo Viên Hướng Dẫn");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Nhóm thực hiện");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4ActionPerformed

    private void q7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7ActionPerformed

    private void qThuDucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qThuDucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qThuDucActionPerformed

    private void btnTinhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhToanActionPerformed
        // TODO add your handling code here:
        btnChonLai.setEnabled(false);
        timKetQua();
        String duongdi = "Đường đi: ";
        for (int i = 0; i <= quan - 1; i++) {
            if (ketQua.get(i) == 13) {
                duongdi += "Thủ đức ->";
            } else if (ketQua.get(i) == 14) {
                duongdi += "Bình Thạnh ->";
            } else if (ketQua.get(i) == 15) {
                duongdi += "Phú Nhuận ->";
            } else if (ketQua.get(i) == 16) {
                duongdi += "Gò Vấp ->";
            } else if (ketQua.get(i) == 17) {
                duongdi += "Tân Phú ->";
            } else if (ketQua.get(i) == 18) {
                duongdi += "Tân Bình ->";
            } else if (ketQua.get(i) == 19) {
                duongdi += "Bình Tân ->";
            } else {
                duongdi += ketQua.get(i) + " ->";
            }
        }
        if (ketQua.get(quan) == 13) {
            duongdi += "Thủ đức";
        } else if (ketQua.get(quan) == 14) {
            duongdi += "Bình Thạnh";
        } else if (ketQua.get(quan) == 15) {
            duongdi += "Phú Nhuận";
        } else if (ketQua.get(quan) == 16) {
            duongdi += "Gò Vấp";
        } else if (ketQua.get(quan) == 17) {
            duongdi += "Tân Phú";
        } else if (ketQua.get(quan) == 18) {
            duongdi += "Tân Bình";
        } else if (ketQua.get(quan) == 19) {
            duongdi += "Bình Tân";
        } else {
            duongdi += ketQua.get(quan);
        }
        txtDuongDi.setText(duongdi);
        lbChiPhi.setText("Chi phí: " + min);
    }//GEN-LAST:event_btnTinhToanActionPerformed

    private void qTanBinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qTanBinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qTanBinhActionPerformed

    private void btnChonLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonLaiActionPerformed
        // TODO add your handling code here:
        txtQuanXuatPhat.setEnabled(true);
        ThuDuc.setEnabled(true);
        BinhThanh.setEnabled(true);
        BinhTan.setEnabled(true);
        GoVap.setEnabled(true);
        TanBinh.setEnabled(true);
        TanPhu.setEnabled(true);
        PhuNhuan.setEnabled(true);
        btnXacNhan.setEnabled(true);
    }//GEN-LAST:event_btnChonLaiActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtQuanXuatPhat.getText()) == 1 || Integer.parseInt(txtQuanXuatPhat.getText()) == 2 || Integer.parseInt(txtQuanXuatPhat.getText()) == 3
                    || Integer.parseInt(txtQuanXuatPhat.getText()) == 4 || Integer.parseInt(txtQuanXuatPhat.getText()) == 5 || Integer.parseInt(txtQuanXuatPhat.getText()) == 6
                    || Integer.parseInt(txtQuanXuatPhat.getText()) == 7 || Integer.parseInt(txtQuanXuatPhat.getText()) == 8 || Integer.parseInt(txtQuanXuatPhat.getText()) == 9
                    || Integer.parseInt(txtQuanXuatPhat.getText()) == 10 || Integer.parseInt(txtQuanXuatPhat.getText()) == 11 || Integer.parseInt(txtQuanXuatPhat.getText()) == 12
                    || Integer.parseInt(txtQuanXuatPhat.getText()) == 13 || Integer.parseInt(txtQuanXuatPhat.getText()) == 14 || Integer.parseInt(txtQuanXuatPhat.getText()) == 15
                    || Integer.parseInt(txtQuanXuatPhat.getText()) == 16 || Integer.parseInt(txtQuanXuatPhat.getText()) == 17 || Integer.parseInt(txtQuanXuatPhat.getText()) == 18
                    || Integer.parseInt(txtQuanXuatPhat.getText()) == 19) {
                quanBatDau = Integer.parseInt(txtQuanXuatPhat.getText());
                txtQuanXuatPhat.setEnabled(false);
                ThuDuc.setEnabled(false);
                BinhThanh.setEnabled(false);
                BinhTan.setEnabled(false);
                GoVap.setEnabled(false);
                TanBinh.setEnabled(false);
                TanPhu.setEnabled(false);
                PhuNhuan.setEnabled(false);
                btnXacNhan.setEnabled(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Quận nhập sai hoặc không tồn tại", "Kiểm tra lại quận bắt đầu", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void GoVapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoVapActionPerformed
        // TODO add your handling code here:
        txtQuanXuatPhat.setText("16");
    }//GEN-LAST:event_GoVapActionPerformed

    private void ThuDucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThuDucActionPerformed
        // TODO add your handling code here:
        txtQuanXuatPhat.setText("13");
    }//GEN-LAST:event_ThuDucActionPerformed

    private void BinhThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinhThanhActionPerformed
        // TODO add your handling code here:
        txtQuanXuatPhat.setText("14");
    }//GEN-LAST:event_BinhThanhActionPerformed

    private void PhuNhuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhuNhuanActionPerformed

        // TODO add your handling code here:
        txtQuanXuatPhat.setText("15");
    }//GEN-LAST:event_PhuNhuanActionPerformed

    private void TanPhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanPhuActionPerformed
        // TODO add your handling code here:
        txtQuanXuatPhat.setText("17");
    }//GEN-LAST:event_TanPhuActionPerformed

    private void TanBinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanBinhActionPerformed
        // TODO add your handling code here:
        txtQuanXuatPhat.setText("18");
    }//GEN-LAST:event_TanBinhActionPerformed

    private void BinhTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinhTanActionPerformed
        // TODO add your handling code here:
        txtQuanXuatPhat.setText("19");
    }//GEN-LAST:event_BinhTanActionPerformed

    private void btnChayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChayActionPerformed
        // TODO add your handling code here:
        if (quanBatDau == 1) {
            q1.setBackground(Color.gray);
        } else if (quanBatDau == 2) {
            q2.setBackground(Color.gray);
        } else if (quanBatDau == 3) {
            q3.setBackground(Color.gray);
        } else if (quanBatDau == 4) {
            q4.setBackground(Color.gray);
        } else if (quanBatDau == 5) {
            q5.setBackground(Color.gray);
        } else if (quanBatDau == 6) {
            q6.setBackground(Color.gray);
        } else if (quanBatDau == 7) {
            q7.setBackground(Color.gray);
        } else if (quanBatDau == 8) {
            q8.setBackground(Color.gray);
        } else if (quanBatDau == 9) {
            q9.setBackground(Color.gray);
        } else if (quanBatDau == 10) {
            q10.setBackground(Color.gray);
        } else if (quanBatDau == 11) {
            q11.setBackground(Color.gray);
        } else if (quanBatDau == 12) {
            q12.setBackground(Color.gray);
        } else if (quanBatDau == 13) {
            qThuDuc.setBackground(Color.gray);
        } else if (quanBatDau == 14) {
            qBinhThanh.setBackground(Color.gray);
        } else if (quanBatDau == 15) {
            qPhuNhuan.setBackground(Color.gray);
        } else if (quanBatDau == 16) {
            qGoVap.setBackground(Color.gray);
        } else if (quanBatDau == 17) {
            qTanPhu.setBackground(Color.gray);
        } else if (quanBatDau == 18) {
            qTanBinh.setBackground(Color.gray);
        } else if (quanBatDau == 19) {
            qBinhTan.setBackground(Color.gray);
        }
    }//GEN-LAST:event_btnChayActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:

        int j = indexdi + 1; //bntNext
        if ((ketQua.get(indexdi) == 1 && ketQua.get(j) == 2) || (ketQua.get(indexdi) == 2 && ketQua.get(j) == 1)) {
            d1_2.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 1 && ketQua.get(j) == 3) || (ketQua.get(indexdi) == 3 && ketQua.get(j) == 1)) {
            d1_3.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 1 && ketQua.get(j) == 4) || (ketQua.get(indexdi) == 4 && ketQua.get(j) == 1)) {
            d1_4.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 1 && ketQua.get(j) == 5) || (ketQua.get(indexdi) == 5 && ketQua.get(j) == 1)) {
            d1_5.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 1 && ketQua.get(j) == 14) || (ketQua.get(indexdi) == 14 && ketQua.get(j) == 1)) {
            d1_14.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 1 && ketQua.get(j) == 15) || (ketQua.get(indexdi) == 15 && ketQua.get(j) == 1)) {
            d1_15.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 2 && ketQua.get(j) == 7) || (ketQua.get(indexdi) == 7 && ketQua.get(j) == 2)) {
            d2_7.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 2 && ketQua.get(j) == 9) || (ketQua.get(indexdi) == 9 && ketQua.get(j) == 2)) {
            d2_9.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 2 && ketQua.get(j) == 14) || (ketQua.get(indexdi) == 14 && ketQua.get(j) == 2)) {
            d2_14.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 3 && ketQua.get(j) == 5) || (ketQua.get(indexdi) == 5 && ketQua.get(j) == 4)) {
            d3_5.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 3 && ketQua.get(j) == 10) || (ketQua.get(indexdi) == 10 && ketQua.get(j) == 3)) {
            d3_10.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 3 && ketQua.get(j) == 15) || (ketQua.get(indexdi) == 15 && ketQua.get(j) == 3)) {
            d3_15.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 3 && ketQua.get(j) == 18) || (ketQua.get(indexdi) == 18 && ketQua.get(j) == 3)) {
            d3_18.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 4 && ketQua.get(j) == 5) || (ketQua.get(indexdi) == 5 && ketQua.get(j) == 4)) {
            d4_5.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 4 && ketQua.get(j) == 7) || (ketQua.get(indexdi) == 7 && ketQua.get(j) == 4)) {
            d4_7.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 4 && ketQua.get(j) == 8) || (ketQua.get(indexdi) == 8 && ketQua.get(j) == 4)) {
            d4_8.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 5 && ketQua.get(j) == 6) || (ketQua.get(indexdi) == 6 && ketQua.get(j) == 5)) {
            d5_6.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 8 && ketQua.get(j) == 5) || (ketQua.get(indexdi) == 5 && ketQua.get(j) == 8)) {
            d5_8.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 5 && ketQua.get(j) == 10) || (ketQua.get(indexdi) == 10 && ketQua.get(j) == 5)) {
            d5_10.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 5 && ketQua.get(j) == 11) || (ketQua.get(indexdi) == 11 && ketQua.get(j) == 5)) {
            d5_11.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 6 && ketQua.get(j) == 8) || (ketQua.get(indexdi) == 8 && ketQua.get(j) == 6)) {
            d6_8.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 6 && ketQua.get(j) == 19) || (ketQua.get(indexdi) == 19 && ketQua.get(j) == 6)) {
            d6_19.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 11 && ketQua.get(j) == 6) || (ketQua.get(indexdi) == 6 && ketQua.get(j) == 11)) {
            d6_11.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 7 && ketQua.get(j) == 8) || (ketQua.get(indexdi) == 8 && ketQua.get(j) == 7)) {
            d7_8.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 8 && ketQua.get(j) == 19) || (ketQua.get(indexdi) == 19 && ketQua.get(j) == 8)) {
            d8_19.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 9 && ketQua.get(j) == 13) || (ketQua.get(indexdi) == 13 && ketQua.get(j) == 9)) {
            d9_13.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 10 && ketQua.get(j) == 11) || (ketQua.get(indexdi) == 11 && ketQua.get(j) == 10)) {
            d10_11.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 10 && ketQua.get(j) == 18) || (ketQua.get(indexdi) == 18 && ketQua.get(j) == 10)) {
            d10_18.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 11 && ketQua.get(j) == 17) || (ketQua.get(indexdi) == 17 && ketQua.get(j) == 11)) {
            d11_17.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 11 && ketQua.get(j) == 18) || (ketQua.get(indexdi) == 18 && ketQua.get(j) == 11)) {
            d11_18.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 12 && ketQua.get(j) == 13) || (ketQua.get(indexdi) == 13 && ketQua.get(j) == 12)) {
            d12_13.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 12 && ketQua.get(j) == 16) || (ketQua.get(indexdi) == 16 && ketQua.get(j) == 12)) {
            d12_16.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 12 && ketQua.get(j) == 17) || (ketQua.get(indexdi) == 17 && ketQua.get(j) == 12)) {
            d12_17.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 13 && ketQua.get(j) == 14) || (ketQua.get(indexdi) == 14 && ketQua.get(j) == 13)) {
            d13_14.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 13 && ketQua.get(j) == 16) || (ketQua.get(indexdi) == 16 && ketQua.get(j) == 13)) {
            d13_16.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 14 && ketQua.get(j) == 15) || (ketQua.get(indexdi) == 15 && ketQua.get(j) == 14)) {
            d14_15.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 14 && ketQua.get(j) == 16) || (ketQua.get(indexdi) == 16 && ketQua.get(j) == 14)) {
            d14_16.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 15 && ketQua.get(j) == 16) || (ketQua.get(indexdi) == 16 && ketQua.get(j) == 15)) {
            d15_16.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 15 && ketQua.get(j) == 18) || (ketQua.get(indexdi) == 18 && ketQua.get(j) == 15)) {
            d15_18.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 16 && ketQua.get(j) == 18) || (ketQua.get(indexdi) == 18 && ketQua.get(j) == 16)) {
            d16_18.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 17 && ketQua.get(j) == 18) || (ketQua.get(indexdi) == 18 && ketQua.get(j) == 19)) {
            d17_18.setForeground(Color.blue);
        } else if ((ketQua.get(indexdi) == 17 && ketQua.get(j) == 19) || (ketQua.get(indexdi) == 17 && ketQua.get(j) == 19)) {
            d17_19.setForeground(Color.blue);
        }
        if (ketQua.get(j) == 1) {
            q1.setBackground(Color.green);
        } else if (ketQua.get(j) == 2) {
            q2.setBackground(Color.green);
        } else if (ketQua.get(j) == 3) {
            q3.setBackground(Color.green);
        } else if (ketQua.get(j) == 4) {
            q4.setBackground(Color.green);
        } else if (ketQua.get(j) == 5) {
            q5.setBackground(Color.green);
        } else if (ketQua.get(j) == 6) {
            q6.setBackground(Color.green);
        } else if (ketQua.get(j) == 7) {
            q7.setBackground(Color.green);
        } else if (ketQua.get(j) == 8) {
            q8.setBackground(Color.green);
        } else if (ketQua.get(j) == 9) {
            q9.setBackground(Color.green);
        } else if (ketQua.get(j) == 10) {
            q10.setBackground(Color.green);
        } else if (ketQua.get(j) == 11) {
            q11.setBackground(Color.green);
        } else if (ketQua.get(j) == 12) {
            q12.setBackground(Color.green);
        } else if (ketQua.get(j) == 13) {
            qThuDuc.setBackground(Color.green);
        } else if (ketQua.get(j) == 14) {
            qBinhThanh.setBackground(Color.green);
        } else if (ketQua.get(j) == 15) {
            qPhuNhuan.setBackground(Color.green);
        } else if (ketQua.get(j) == 16) {
            qGoVap.setBackground(Color.green);
        } else if (ketQua.get(j) == 17) {
            qTanPhu.setBackground(Color.green);
        } else if (ketQua.get(j) == 18) {
            qTanBinh.setBackground(Color.green);
        } else if (ketQua.get(j) == 19) {
            qBinhTan.setBackground(Color.green);
        }
        indexdi++;
    }//GEN-LAST:event_btnNextActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:        
        mtTP = new DuongDi[20][20]; // chua cost duong di
        generator = new Random();
        mtKe = new int[20][20]; //
        luuDuongTam = new int[20];// 1 mang 20 ki so(tu quan bat )... qua cac quan 
        Heuristic = new int[20];;// tung` di qua r
        btnChonLai.setEnabled(true);
        luuDuongDi = new ArrayList<>();//luu chu trinh hamilton
        d = 0;//so duong di(chu trinh)
        index = 0;//chu trinh tai luuduongdi[index] ngan nhat
        min = 0;//cost thap nhat de di
        ketQua = new ArrayList<>();
        quanBatDau = 1;
        indexdi = 0;
        txtQuanXuatPhat.setText("1");
        initCost(); // ramdom cost
        initMatran();
        luuDuongTam[0] = 1;
        int i = 1;
        d = 0;
        Hamilton(luuDuongTam, Heuristic, i);
        //inmanhinhmtKe();
        timIndexNganNhat();
        q1.setBackground(Color.white);
        q2.setBackground(Color.white);
        q3.setBackground(Color.white);
        q4.setBackground(Color.white);
        q5.setBackground(Color.white);
        q6.setBackground(Color.white);
        q7.setBackground(Color.white);
        q8.setBackground(Color.white);
        q9.setBackground(Color.white);
        q10.setBackground(Color.white);
        q11.setBackground(Color.white);
        q12.setBackground(Color.white);
        qBinhTan.setBackground(Color.white);
        qBinhThanh.setBackground(Color.white);
        qGoVap.setBackground(Color.white);
        qPhuNhuan.setBackground(Color.white);
        qTanBinh.setBackground(Color.white);
        qTanPhu.setBackground(Color.white);
        qThuDuc.setBackground(Color.white);
        lbChiPhi.setText("Chi Phí: ");
        txtDuongDi.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "     ***Trường Đại học Công Nghiệp Thực Phẩm***\n                **Khoa công nghệ thông tin**\nLập Trình Java: Thầy NGUYỄN THẾ HỮU\nTrí Tuệ Nhân Tạo: Thầy NGÔ DƯƠNG HÀ", "Giáo viên hướng dẫn", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String noidung = "            ***Các thành viên***\n"
                + "Trương Công Hậu. MSSV:2001180261\n"
                + "Nguyễn Thành Nhân. MSSV:2001180088\n"
                + "Nguyễn Hòa Trung Hiếu. MSSV:2001180437\n";
        JOptionPane.showMessageDialog(null, noidung, "Thành viên thực hiện", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiDonRac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiDonRac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiDonRac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiDonRac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiDonRac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BinhTan;
    private javax.swing.JButton BinhThanh;
    private javax.swing.JButton GoVap;
    private javax.swing.JButton PhuNhuan;
    private javax.swing.JButton TanBinh;
    private javax.swing.JButton TanPhu;
    private javax.swing.JButton ThuDuc;
    private javax.swing.JButton btnChay;
    private javax.swing.JButton btnChonLai;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnTinhToan;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel c10_11;
    private javax.swing.JLabel c10_18;
    private javax.swing.JLabel c11_17;
    private javax.swing.JLabel c11_18;
    private javax.swing.JLabel c12_13;
    private javax.swing.JLabel c12_16;
    private javax.swing.JLabel c12_17;
    private javax.swing.JLabel c13_14;
    private javax.swing.JLabel c13_16;
    private javax.swing.JLabel c14_15;
    private javax.swing.JLabel c14_16;
    private javax.swing.JLabel c15_16;
    private javax.swing.JLabel c15_18;
    private javax.swing.JLabel c16_18;
    private javax.swing.JLabel c17_18;
    private javax.swing.JLabel c17_19;
    private javax.swing.JLabel c1_14;
    private javax.swing.JLabel c1_15;
    private javax.swing.JLabel c1_2;
    private javax.swing.JLabel c1_3;
    private javax.swing.JLabel c1_4;
    private javax.swing.JLabel c1_5;
    private javax.swing.JLabel c2_14;
    private javax.swing.JLabel c2_7;
    private javax.swing.JLabel c2_9;
    private javax.swing.JLabel c3_10;
    private javax.swing.JLabel c3_15;
    private javax.swing.JLabel c3_18;
    private javax.swing.JLabel c3_5;
    private javax.swing.JLabel c4_5;
    private javax.swing.JLabel c4_7;
    private javax.swing.JLabel c4_8;
    private javax.swing.JLabel c5_10;
    private javax.swing.JLabel c5_11;
    private javax.swing.JLabel c5_6;
    private javax.swing.JLabel c5_8;
    private javax.swing.JLabel c6_11;
    private javax.swing.JLabel c6_19;
    private javax.swing.JLabel c6_8;
    private javax.swing.JLabel c7_8;
    private javax.swing.JLabel c8_19;
    private javax.swing.JLabel c9_13;
    private javax.swing.JSeparator d10_11;
    private javax.swing.JSeparator d10_18;
    private javax.swing.JSeparator d11_17;
    private javax.swing.JSeparator d11_18;
    private javax.swing.JSeparator d12_13;
    private javax.swing.JSeparator d12_16;
    private javax.swing.JSeparator d12_17;
    private javax.swing.JSeparator d13_14;
    private javax.swing.JSeparator d13_16;
    private javax.swing.JSeparator d14_15;
    private javax.swing.JSeparator d14_16;
    private javax.swing.JSeparator d15_16;
    private javax.swing.JSeparator d15_18;
    private javax.swing.JSeparator d16_18;
    private javax.swing.JSeparator d17_18;
    private javax.swing.JSeparator d17_19;
    private javax.swing.JSeparator d1_14;
    private javax.swing.JSeparator d1_15;
    private javax.swing.JSeparator d1_2;
    private javax.swing.JSeparator d1_3;
    private javax.swing.JSeparator d1_4;
    private javax.swing.JSeparator d1_5;
    private javax.swing.JSeparator d2_14;
    private javax.swing.JSeparator d2_7;
    private javax.swing.JSeparator d2_9;
    private javax.swing.JSeparator d3_10;
    private javax.swing.JSeparator d3_15;
    private javax.swing.JSeparator d3_18;
    private javax.swing.JSeparator d3_5;
    private javax.swing.JSeparator d4_5;
    private javax.swing.JSeparator d4_7;
    private javax.swing.JSeparator d4_8;
    private javax.swing.JSeparator d5_10;
    private javax.swing.JSeparator d5_11;
    private javax.swing.JSeparator d5_6;
    private javax.swing.JSeparator d5_8;
    private javax.swing.JSeparator d6_11;
    private javax.swing.JSeparator d6_19;
    private javax.swing.JSeparator d6_8;
    private javax.swing.JSeparator d7_8;
    private javax.swing.JSeparator d8_19;
    private javax.swing.JSeparator d9_13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbChiPhi;
    private javax.swing.JLabel lbDuongDi;
    private javax.swing.JButton q1;
    private javax.swing.JButton q10;
    private javax.swing.JButton q11;
    private javax.swing.JButton q12;
    private javax.swing.JButton q2;
    private javax.swing.JButton q3;
    private javax.swing.JButton q4;
    private javax.swing.JButton q5;
    private javax.swing.JButton q6;
    private javax.swing.JButton q7;
    private javax.swing.JButton q8;
    private javax.swing.JButton q9;
    private javax.swing.JButton qBinhTan;
    private javax.swing.JButton qBinhThanh;
    private javax.swing.JButton qGoVap;
    private javax.swing.JButton qPhuNhuan;
    private javax.swing.JButton qTanBinh;
    private javax.swing.JButton qTanPhu;
    private javax.swing.JButton qThuDuc;
    private javax.swing.JTextArea txtDuongDi;
    private javax.swing.JTextField txtQuanXuatPhat;
    // End of variables declaration//GEN-END:variables

    private void initMatran()//ma trận thêm dữ liệu vào mtTP mà mtKE
    {
        for (int i = 1; i <= 19; i++) {
            for (int j = 1; j <= 19; j++) {
                mtTP[i][j] = new DuongDi();
                if (i == j) {
                    mtTP[i][j].setCost(-1);//k ton tai duong di do
                    mtKe[i][j] = 0;

                } else if (((i == 1) && (j == 2)) || ((i == 2) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_2.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 3)) || ((i == 3) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_3.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 4)) || ((i == 4) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_4.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 5)) || ((i == 5) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_5.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 14)) || ((i == 14) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_14.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 2)) || ((i == 2) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_2.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 2)) || ((i == 2) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_2.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 2)) || ((i == 2) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_2.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 2)) || ((i == 2) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_2.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 2)) || ((i == 2) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_2.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 2)) || ((i == 2) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_2.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 1) && (j == 15)) || ((i == 15) && (j == 1))) {
                    mtTP[i][j].setCost(Integer.parseInt(c1_15.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 2) && (j == 7)) || ((i == 7) && (j == 2))) {
                    mtTP[i][j].setCost(Integer.parseInt(c2_7.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 2) && (j == 9)) || ((i == 9) && (j == 2))) {
                    mtTP[i][j].setCost(Integer.parseInt(c2_9.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 2) && (j == 14)) || ((i == 14) && (j == 2))) {
                    mtTP[i][j].setCost(Integer.parseInt(c2_14.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 3) && (j == 5)) || ((i == 5) && (j == 3))) {
                    mtTP[i][j].setCost(Integer.parseInt(c3_5.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 3) && (j == 10)) || ((i == 10) && (j == 3))) {
                    mtTP[i][j].setCost(Integer.parseInt(c3_10.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 3) && (j == 15)) || ((i == 15) && (j == 3))) {
                    mtTP[i][j].setCost(Integer.parseInt(c3_15.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 3) && (j == 18)) || ((i == 18) && (j == 3))) {
                    mtTP[i][j].setCost(Integer.parseInt(c3_18.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 4) && (j == 5)) || ((i == 5) && (j == 4))) {
                    mtTP[i][j].setCost(Integer.parseInt(c4_5.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 4) && (j == 5)) || ((i == 5) && (j == 4))) {
                    mtTP[i][j].setCost(Integer.parseInt(c4_5.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 4) && (j == 7)) || ((i == 7) && (j == 4))) {
                    mtTP[i][j].setCost(Integer.parseInt(c4_7.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 4) && (j == 8)) || ((i == 8) && (j == 4))) {
                    mtTP[i][j].setCost(Integer.parseInt(c4_8.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 5) && (j == 6)) || ((i == 6) && (j == 5))) {
                    mtTP[i][j].setCost(Integer.parseInt(c5_6.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 5) && (j == 10)) || ((i == 10) && (j == 5))) {
                    mtTP[i][j].setCost(Integer.parseInt(c5_10.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 5) && (j == 8)) || ((i == 8) && (j == 5))) {
                    mtTP[i][j].setCost(Integer.parseInt(c5_8.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 5) && (j == 11)) || ((i == 11) && (j == 5))) {
                    mtTP[i][j].setCost(Integer.parseInt(c5_11.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 6) && (j == 8)) || ((i == 8) && (j == 6))) {
                    mtTP[i][j].setCost(Integer.parseInt(c6_8.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 6) && (j == 11)) || ((i == 11) && (j == 6))) {
                    mtTP[i][j].setCost(Integer.parseInt(c6_11.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 6) && (j == 19)) || ((i == 19) && (j == 6))) {
                    mtTP[i][j].setCost(Integer.parseInt(c6_19.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 7) && (j == 8)) || ((i == 8) && (j == 7))) {
                    mtTP[i][j].setCost(Integer.parseInt(c7_8.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 8) && (j == 19)) || ((i == 19) && (j == 8))) {
                    mtTP[i][j].setCost(Integer.parseInt(c8_19.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 9) && (j == 13)) || ((i == 13) && (j == 9))) {
                    mtTP[i][j].setCost(Integer.parseInt(c9_13.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 10) && (j == 11)) || ((i == 11) && (j == 10))) {
                    mtTP[i][j].setCost(Integer.parseInt(c10_11.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 10) && (j == 18)) || ((i == 18) && (j == 10))) {
                    mtTP[i][j].setCost(Integer.parseInt(c10_18.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 11) && (j == 17)) || ((i == 17) && (j == 11))) {
                    mtTP[i][j].setCost(Integer.parseInt(c11_17.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 11) && (j == 18)) || ((i == 18) && (j == 11))) {
                    mtTP[i][j].setCost(Integer.parseInt(c11_18.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 12) && (j == 13)) || ((i == 13) && (j == 12))) {
                    mtTP[i][j].setCost(Integer.parseInt(c12_13.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 12) && (j == 16)) || ((i == 16) && (j == 12))) {
                    mtTP[i][j].setCost(Integer.parseInt(c12_16.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 12) && (j == 17)) || ((i == 17) && (j == 12))) {
                    mtTP[i][j].setCost(Integer.parseInt(c12_17.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 13) && (j == 14)) || ((i == 14) && (j == 13))) {
                    mtTP[i][j].setCost(Integer.parseInt(c13_14.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 13) && (j == 16)) || ((i == 16) && (j == 13))) {
                    mtTP[i][j].setCost(Integer.parseInt(c13_16.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 14) && (j == 15)) || ((i == 15) && (j == 14))) {
                    mtTP[i][j].setCost(Integer.parseInt(c14_15.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 14) && (j == 16)) || ((i == 16) && (j == 14))) {
                    mtTP[i][j].setCost(Integer.parseInt(c14_16.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 15) && (j == 16)) || ((i == 16) && (j == 15))) {
                    mtTP[i][j].setCost(Integer.parseInt(c15_16.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 15) && (j == 18)) || ((i == 18) && (j == 15))) {
                    mtTP[i][j].setCost(Integer.parseInt(c15_18.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 16) && (j == 18)) || ((i == 18) && (j == 16))) {
                    mtTP[i][j].setCost(Integer.parseInt(c16_18.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 17) && (j == 18)) || ((i == 18) && (j == 17))) {
                    mtTP[i][j].setCost(Integer.parseInt(c17_18.getText()));
                    mtKe[i][j] = 1;

                } else if (((i == 17) && (j == 19)) || ((i == 19) && (j == 17))) {
                    mtTP[i][j].setCost(Integer.parseInt(c17_19.getText()));
                    mtKe[i][j] = 1;

                } else {
                    mtKe[i][j] = 0;
                    mtTP[i][j].setCost(-1);
                }
            }
        }
    }

    private void initCost() {
        c1_2.setText(generator.nextInt(5) + 5 + "");
        c1_3.setText(generator.nextInt(5) + 5 + "");
        c1_4.setText(generator.nextInt(5) + 5 + "");
        c1_5.setText(generator.nextInt(5) + 5 + "");
        c1_14.setText(generator.nextInt(5) + 5 + "");
        c1_15.setText(generator.nextInt(5) + 5 + "");
        c2_7.setText(generator.nextInt(5) + 5 + "");
        c2_9.setText(generator.nextInt(5) + 5 + "");
        c2_14.setText(generator.nextInt(5) + 5 + "");
        c3_5.setText(generator.nextInt(5) + 5 + "");
        c3_10.setText(generator.nextInt(5) + 5 + "");
        c3_15.setText(generator.nextInt(5) + 5 + "");
        c3_18.setText(generator.nextInt(5) + 5 + "");
        c4_5.setText(generator.nextInt(5) + 5 + "");
        c4_7.setText(generator.nextInt(5) + 5 + "");
        c4_8.setText(generator.nextInt(5) + 5 + "");
        c5_6.setText(generator.nextInt(5) + 5 + "");
        c5_8.setText(generator.nextInt(5) + 5 + "");
        c5_10.setText(generator.nextInt(5) + 5 + "");
        c5_11.setText(generator.nextInt(5) + 5 + "");
        c6_8.setText(generator.nextInt(5) + 5 + "");
        c6_11.setText(generator.nextInt(5) + 5 + "");
        c6_19.setText(generator.nextInt(5) + 5 + "");
        c7_8.setText(generator.nextInt(5) + 5 + "");
        c8_19.setText(generator.nextInt(5) + 5 + "");
        c9_13.setText(generator.nextInt(5) + 5 + "");
        c10_11.setText(generator.nextInt(5) + 5 + "");
        c10_18.setText(generator.nextInt(5) + 5 + "");
        c11_17.setText(generator.nextInt(5) + 5 + "");
        c11_18.setText(generator.nextInt(5) + 5 + "");
        c12_13.setText(generator.nextInt(5) + 5 + "");
        c12_16.setText(generator.nextInt(5) + 5 + "");
        c12_17.setText(generator.nextInt(5) + 5 + "");
        c13_14.setText(generator.nextInt(5) + 5 + "");
        c13_16.setText(generator.nextInt(5) + 5 + "");
        c14_15.setText(generator.nextInt(5) + 5 + "");
        c14_16.setText(generator.nextInt(5) + 5 + "");
        c15_16.setText(generator.nextInt(5) + 5 + "");
        c15_18.setText(generator.nextInt(5) + 5 + "");
        c16_18.setText(generator.nextInt(5) + 5 + "");
        c17_18.setText(generator.nextInt(5) + 5 + "");
        c17_19.setText(generator.nextInt(5) + 5 + "");

    }

    void Hamilton(int B[], int C[], int i)//luu duong di, luu heurictis, index(k dc trung`)
    { //ktra mtKe đủ 20 nút thì là chu trình hamilton.. k phai thi skip
        int j;
        for (j = 1; j <= quan; j++) {
            if (mtKe[B[i - 1]][j] == 1 && C[j] == 0) {
                B[i] = j;
                C[j] = 1;
                if (i < quan) {
                    Hamilton(B, C, i + 1);
                } else if (B[i] == B[0]) {
                    luuchutrinh();
                }
                //inmanhinhchutrinh();
                C[j] = 0;
            }
        }
    }

    private void inmanhinhmtKe() {
        for (int i = 1; i <= 19; i++) {
            for (int j = 1; j <= 19; j++) {
                System.out.print(mtKe[i][j] + " ");
            }
            System.out.println();
        }
    }

    private void inmanhinhchutrinh() {
        this.d++;
        System.out.print("Chu trinh: ");
        for (int i = quan; i >= 0; i--) {
            System.out.print(this.luuDuongTam[i] + " ");
        }
        System.out.println();
    }

    private void luuchutrinh() {
        d++;
        ArrayList<Integer> duongdi = new ArrayList<>();
        for (int i = quan; i >= 0; i--) {
            duongdi.add(luuDuongTam[i]);
        }
        luuDuongDi.add(duongdi);
    }

    private void timIndexNganNhat() {

        for (int i = 0; i < quan; i++) {
            int j = i + 1;
            min += mtTP[Integer.parseInt(luuDuongDi.get(index).get(i).toString())][Integer.parseInt(luuDuongDi.get(index).get(j).toString())].getCost();
        }

        for (int i = 1; i < luuDuongDi.size(); i++) {
            int temp = 0;
            for (int j = 0; j < quan; j++) {
                int f = j + 1;
                temp += mtTP[Integer.parseInt(luuDuongDi.get(i).get(j).toString())][Integer.parseInt(luuDuongDi.get(i).get(f).toString())].getCost();
            }
            if (temp < min) {
                min = temp;
                index = i;
            }
        }
    }

    private void timKetQua() // in ra man hinh
    {
        if (quanBatDau == 1) {
            for (int i = 0; i <= quan; i++) {
                ketQua.add(Integer.parseInt(luuDuongDi.get(index).get(i).toString()));
            }
        } else {
            int dem = 0;
            for (; dem <= quan; dem++) {
                if (Integer.parseInt(luuDuongDi.get(index).get(dem).toString()) == quanBatDau) {
                    break;
                }
            }
            for (int i = dem; i <= quan; i++) {
                ketQua.add(Integer.parseInt(luuDuongDi.get(index).get(i).toString()));
            }
            for (int i = 1; i < dem; i++) {
                ketQua.add(Integer.parseInt(luuDuongDi.get(index).get(i).toString()));
            }
            ketQua.add(quanBatDau);
        }
    }

}
